# Generated by Django 5.2.9 on 2026-01-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_exam_auto_enroll_course_students_exam_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ip_changed_during_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='keyboard_shortcut_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='right_click_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='time_taken_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
